name: build and push

on:
  push:
    branches:
      - "deploy_vercel"

# env:
#   # Use docker.io for Docker Hub if empty
#   REGISTRY: docker.io
#   # github.repository as <account>/<repo>
#   IMAGE_NAME: ${{ github.repo }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: xiaomu1993/notion-next
          tags: |
            type=ref,event=tag

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: latest
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            NOTION_PAGE_ID=${{secrets.NOTION_PAGE_ID}}
            NEXT_PUBLIC_BEI_AN=${{secrets.BEI_AN}}
